# Generated by Django 4.2.11 on 2025-12-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='county_image',
            new_name='country_image',
        ),
    ]
