# Generated by Django 4.2.11 on 2025-12-17 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_rename_county_image_country_country_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='chek_out',
            new_name='check_out',
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='booking_app.hotel'),
        ),
    ]
