# Generated by Django 5.1.3 on 2025-12-19 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_alter_booking_id_alter_city_id_alter_country_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('стандарт', 'стандарт'), ('семейный', 'семейный'), ('одноместный', 'одноместный'), ('люкс', 'люкс')], max_length=20),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking_app.room'),
        ),
    ]
